# Generated by Django 5.0.4 on 2024-04-11 23:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('Id_group', models.AutoField(primary_key=True, serialize=False)),
                ('GroupName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Id_member', models.AutoField(primary_key=True, serialize=False)),
                ('Position', models.CharField(choices=[('0', 'Quản lý dự án'), ('1', 'Nhân viên'), ('2', 'Khách hàng')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Id_project', models.AutoField(primary_key=True, serialize=False)),
                ('NameProject', models.TextField()),
                ('Description', models.TextField()),
                ('Budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SupportChat',
            fields=[
                ('Id_supportChat', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id_user', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.TextField()),
                ('Spice', models.CharField(max_length=10)),
                ('EncodePass', models.CharField(max_length=64)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Avatar', models.ImageField(upload_to='avatars/')),
                ('TypeUser', models.CharField(choices=[('0', 'Thành viên phát triển dự án'), ('1', 'Khách hàng')], max_length=1)),
                ('Online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('Id_assign', models.AutoField(primary_key=True, serialize=False)),
                ('Id_group', models.IntegerField(default=None, null=True)),
                ('Id_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('Id_participant', models.AutoField(primary_key=True, serialize=False)),
                ('Position', models.CharField(choices=[('0', 'Trưởng nhóm'), ('1', 'Thành viên')], max_length=1)),
                ('Id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
                ('Id_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Id_message', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('SendDate', models.DateTimeField(auto_now=True)),
                ('Id_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('Id_phase', models.AutoField(primary_key=True, serialize=False)),
                ('PhaseName', models.TextField()),
                ('Order', models.IntegerField()),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='Id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
        migrations.CreateModel(
            name='ProjectRepost',
            fields=[
                ('Id_repost', models.AutoField(primary_key=True, serialize=False)),
                ('Progress', models.TextField()),
                ('Risk', models.TextField(null=True)),
                ('Propose', models.TextField(null=True)),
                ('DateRepost', models.DateTimeField(auto_now=True)),
                ('Id_reposter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('Id_repost', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Result', models.TextField()),
                ('RealStartDate', models.DateField()),
                ('RealEndDate', models.DateField()),
                ('DateRepost', models.DateTimeField(auto_now=True)),
                ('Id_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assign')),
            ],
        ),
        migrations.CreateModel(
            name='SharingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.TextField()),
                ('UploadDate', models.DateTimeField(auto_now=True)),
                ('File', models.FileField(upload_to='sharingFiles/')),
                ('Id_member_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
                ('Id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('Reply', models.BooleanField(default=True)),
                ('SendDate', models.DateTimeField(auto_now=True)),
                ('Id_supportChat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supportchat')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Id_task', models.AutoField(primary_key=True, serialize=False)),
                ('TaskName', models.TextField()),
                ('Order', models.IntegerField()),
                ('Description', models.TextField()),
                ('Budget', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Id_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.phase')),
            ],
        ),
        migrations.AddField(
            model_name='assign',
            name='Id_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task'),
        ),
        migrations.AddField(
            model_name='supportchat',
            name='Id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AddField(
            model_name='member',
            name='Id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('Id_call', models.AutoField(primary_key=True, serialize=False)),
                ('Limited', models.TextField()),
                ('Id_member_startCall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
        migrations.CreateModel(
            name='VideoConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offer', models.TextField(null=True)),
                ('Answer', models.TextField(null=True)),
                ('IceCaller', models.TextField(null=True)),
                ('IceCallee', models.TextField(null=True)),
                ('Id_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.videocall')),
                ('Id_callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callee_connections', to='main.member')),
                ('Id_caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller_connections', to='main.member')),
            ],
        ),
    ]
