# Generated by Django 5.0.4 on 2024-04-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='Id_group',
            field=models.TextField(default=None, null=True),
        ),
    ]
