# Generated by Django 5.0.4 on 2024-04-27 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_assign_id_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrepost',
            name='Id_reposter',
        ),
    ]
