# Generated by Django 5.0.4 on 2024-04-27 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_projectrepost_id_reposter'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrepost',
            name='Id_project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
    ]
