# Generated by Django 5.0.4 on 2024-04-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projectrepost_id_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocall',
            name='Id_member_startCall',
        ),
    ]
