# Generated by Django 5.0.4 on 2024-05-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_videocall_id_member_startcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='MaxNumber',
            field=models.IntegerField(choices=[(5, '5 thành viên'), (10, '10 thành viên'), (20, '20 thành viên'), (50, '50 thành viên')], default=5),
        ),
    ]
