# Generated by Django 5.0.4 on 2024-05-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_lock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoconnect',
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='videoconnect',
            name='IceCallee',
        ),
        migrations.RemoveField(
            model_name='videoconnect',
            name='IceCaller',
        ),
        migrations.RemoveField(
            model_name='videoconnect',
            name='Offer',
        ),
    ]
