# Generated by Django 5.0.4 on 2024-05-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_participant_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
