# Generated by Django 5.0.4 on 2024-05-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='Progress',
            field=models.IntegerField(default=0),
        ),
    ]
