# Generated by Django 5.0.4 on 2024-05-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_check_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='Id_writer',
            field=models.IntegerField(default=1),
        ),
    ]
