# Generated by Django 5.0.4 on 2024-05-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_check_id_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='AllowFinish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Finished',
            field=models.BooleanField(default=False),
        ),
    ]
