# Generated by Django 5.0.4 on 2024-05-28 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_project_evaluation_project_handover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repost',
            name='RealEndDate',
        ),
    ]
