# Generated by Django 5.0.4 on 2024-05-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_repost_realenddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repost',
            name='DateRepost',
            field=models.DateField(auto_now=True),
        ),
    ]
