# Generated by Django 5.0.4 on 2024-05-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_repost_daterepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repost',
            name='DateRepost',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
